spring.application.name=roamwise
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/roamwise}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}
jwt.secret="RamWiSE is BeST siTe for TrIP USE It"
roamwise.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200, http://localhost:4000}
google.places.api.key=${GOOGLE_PLACES_KEY}
openai.api.key=${OPENAI_API_KEY}
